# /ros2_ws/src/sensors/config/endpoints.yaml
# Source of truth for sensor output topics.
meta:
  generate:
    cpp: false
    python: true

topics:
  ultrasonic_left: "/ultrasonic/left"
  ultrasonic_right: "/ultrasonic/right"
  gps_data: "/gps/data"
  imu_data: "/imu/data"
  compass_data: "/compass/data"
  battery_data: "/battery/data"

nodes:
  ultrasonic_left_node:
    pub:
      range: "@ultrasonic_left"
  ultrasonic_right_node:
    pub:
      range: "@ultrasonic_right"
  gps_node:
    pub:
      gps_data: "@gps_data"
  i2c_sensors_node:
    pub:
      imu_data: "@imu_data"
      compass_data: "@compass_data"
  battery_node:
    pub:
      battery_data: "@battery_data"
