name: ros-barca
version: "3.8"

services:
  jazzy:
    build: ./
    image: polisail:jazzy-desktop
    container_name: ros-barca
    user: "ros"               # make sure UID/GID match host (see Dockerfile note)
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1  # Avoids potential issues with shared memory
    volumes:
      - ../../ros2_ws/src:/home/ros/ros2_ws/src
      - ../../ros2_ws/scripts:/home/ros/ros2_ws/scripts
      - ../../ros2_ws/rosbags:/home/ros/ros2_ws/rosbags
      - ../../ros2_ws/tools:/home/ros/ros2_ws/tools
      # DRI for HW accel (optional but nice)
      - /dev/dri:/dev/dri
      # If you still need XWayland apps:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/ros/.Xauthority:ros
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true
    command: bash
    entrypoint: ""
